apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

commonLabels:
  app: nginx-kustomize

resources:
- nginx-configmap.yaml
- nginx-deployment.yaml
- nginx-service.yaml
