apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>ArgoCD Demo - Kustomize</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>ArgoCD Demo - Kustomize</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: nginx
